# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
# #   Character.create(name: "Luke", movie: movies.first)
#
# clinics = Clinic.create([{ name: "Clinic 1", address: "address 1", number: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 2", address: "address 2", number: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 3", address: "address 3", number: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 4", address: "address 4", number: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 5", address: "address 5", number: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 6", address: "address 6", number: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 7", address: "address 7", number: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 8", address: "address 8", number: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 9", address: "address 9", number: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 10", address: "address 10", number: 10, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 11", address: "address 11", number: 11, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 12", address: "address 12", number: 12, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 13", address: "address 13", number: 13, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 14", address: "address 14", number: 14, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 15", address: "address 15", number: 15, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 16", address: "address 16", number: 16, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 17", address: "address 17", number: 17, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 18", address: "address 18", number: 18, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 19", address: "address 19", number: 19, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 20", address: "address 20", number: 20, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 21", address: "address 21", number: 21, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 22", address: "address 22", number: 22, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 23", address: "address 23", number: 23, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 24", address: "address 24", number: 24, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 25", address: "address 25", number: 25, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 26", address: "address 26", number: 26, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 27", address: "address 27", number: 27, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 28", address: "address 28", number: 28, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 29", address: "address 29", number: 29, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 30", address: "address 30", number: 30, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 31", address: "address 31", number: 31, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 32", address: "address 32", number: 32, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 33", address: "address 33", number: 33, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 34", address: "address 34", number: 34, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 35", address: "address 35", number: 35, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 36", address: "address 36", number: 36, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 37", address: "address 37", number: 37, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 38", address: "address 38", number: 38, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 39", address: "address 39", number: 39, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 40", address: "address 40", number: 40, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 41", address: "address 41", number: 41, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 42", address: "address 42", number: 42, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 43", address: "address 43", number: 43, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 44", address: "address 44", number: 44, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 45", address: "address 45", number: 45, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 46", address: "address 46", number: 46, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 47", address: "address 47", number: 47, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 48", address: "address 48", number: 48, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 49", address: "address 49", number: 49, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 50", address: "address 50", number: 50, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 51", address: "address 51", number: 51, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 52", address: "address 52", number: 52, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 53", address: "address 53", number: 53, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 54", address: "address 54", number: 54, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 55", address: "address 55", number: 55, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 56", address: "address 56", number: 56, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 57", address: "address 57", number: 57, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 58", address: "address 58", number: 58, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 59", address: "address 59", number: 59, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 60", address: "address 60", number: 60, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 61", address: "address 61", number: 61, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 62", address: "address 62", number: 62, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 63", address: "address 63", number: 63, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 64", address: "address 64", number: 64, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 65", address: "address 65", number: 65, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 66", address: "address 66", number: 66, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 67", address: "address 67", number: 67, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 68", address: "address 68", number: 68, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 69", address: "address 69", number: 69, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 70", address: "address 70", number: 70, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 71", address: "address 71", number: 71, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 72", address: "address 72", number: 72, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 73", address: "address 73", number: 73, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 74", address: "address 74", number: 74, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 75", address: "address 75", number: 75, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 76", address: "address 76", number: 76, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 77", address: "address 77", number: 77, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 78", address: "address 78", number: 78, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 79", address: "address 79", number: 79, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 80", address: "address 80", number: 80, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 81", address: "address 81", number: 81, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 82", address: "address 82", number: 82, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 83", address: "address 83", number: 83, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 84", address: "address 84", number: 84, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 85", address: "address 85", number: 85, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 86", address: "address 86", number: 86, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 87", address: "address 87", number: 87, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 88", address: "address 88", number: 88, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 89", address: "address 89", number: 89, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 90", address: "address 90", number: 90, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 91", address: "address 91", number: 91, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 92", address: "address 92", number: 92, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 93", address: "address 93", number: 93, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 94", address: "address 94", number: 94, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 95", address: "address 95", number: 95, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 96", address: "address 96", number: 96, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 97", address: "address 97", number: 97, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 98", address: "address 98", number: 98, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 99", address: "address 99", number: 99, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 },
#                          { name: "Clinic 100", address: "address 100", number: 100, created_at: Date.today.to_s, updated_at: Date.today.to_s, year: 2020 }])
#
# repartments = Repartment.create([{ name: "Repartment 1", block: "A1", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 2", block: "A2", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 3", block: "A3", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s},
#                                  { name: "Repartment 4", block: "A4", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 5", block: "A5", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 6", block: "A6", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 7", block: "A7", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 8", block: "A8", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 9", block: "A9", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 10", block: "A10", clinic_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 11", block: "A11", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 12", block: "A12", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 13", block: "A13", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 14", block: "A14", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 15", block: "A15", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 16", block: "A16", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 17", block: "A17", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 18", block: "A18", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 19", block: "A19", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 20", block: "A20", clinic_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 21", block: "A21", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 22", block: "A22", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 23", block: "A23", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 24", block: "A24", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 25", block: "A25", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 26", block: "B1", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 27", block: "B2", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 28", block: "B3", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 29", block: "B4", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 30", block: "B5", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 31", block: "B6", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 32", block: "B7", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 33", block: "B8", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 34", block: "B9", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 35", block: "B10", clinic_id: 3, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 36", block: "B11", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 37", block: "B12", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 38", block: "B13", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 39", block: "B14", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 40", block: "B15", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 41", block: "B16", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 42", block: "B17", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 43", block: "B18", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 44", block: "B19", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 45", block: "B20", clinic_id: 4, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 46", block: "B21", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 47", block: "B22", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 48", block: "B23", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 49", block: "B24", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 50", block: "B25", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 51", block: "C1", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 52", block: "C2", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 53", block: "C3", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 54", block: "C4", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 55", block: "C5", clinic_id: 5, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 56", block: "C6", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 57", block: "C7", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 58", block: "C8", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 59", block: "C9", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 60", block: "C10", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 61", block: "C11", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 62", block: "C12", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 63", block: "C13", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 64", block: "C14", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 65", block: "C15", clinic_id: 6, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 66", block: "C16", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 67", block: "C17", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 68", block: "C18", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 69", block: "C19", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 70", block: "C20", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 71", block: "C21", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 72", block: "C22", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 73", block: "C23", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 74", block: "C24", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 75", block: "C25", clinic_id: 7, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 76", block: "D1", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 77", block: "D2", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 78", block: "D3", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 79", block: "D4", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 80", block: "D5", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 81", block: "D6", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 82", block: "D7", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 83", block: "D8", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 84", block: "D9", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 85", block: "D10", clinic_id: 8, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 86", block: "D11", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 87", block: "D12", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 88", block: "D13", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 89", block: "D14", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 90", block: "D15", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 91", block: "D16", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 92", block: "D17", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 93", block: "D18", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 94", block: "D19", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 95", block: "D20", clinic_id: 9, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 96", block: "D21", clinic_id: 10, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 97", block: "D22", clinic_id: 10, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 98", block: "D23", clinic_id: 10, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 99", block: "D24", clinic_id: 10, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                                  { name: "Repartment 100", block: "D25", clinic_id: 10, created_at: Date.today.to_s, updated_at: Date.today.to_s }])
#
# connection = ActiveRecord::Base.connection()
# connection.execute("pragma foreign_keys = on")
# connection.execute("INSERT INTO Specializations(name, created_at, updated_at) VALUES
#   ('Specialization 1', datetime(), datetime()),
#   ('Specialization 2', datetime(), datetime()),
#   ('Specialization 3', datetime(), datetime()),
#   ('Specialization 4', datetime(), datetime()),
#   ('Specialization 5', datetime(), datetime()),
#   ('Specialization 6', datetime(), datetime()),
#   ('Specialization 7', datetime(), datetime()),
#   ('Specialization 8', datetime(), datetime()),
#   ('Specialization 9', datetime(), datetime()),
#   ('Specialization 10', datetime(), datetime()),
#   ('Specialization 11', datetime(), datetime()),
#   ('Specialization 12', datetime(), datetime()),
#   ('Specialization 13', datetime(), datetime()),
#   ('Specialization 14', datetime(), datetime()),
#   ('Specialization 15', datetime(), datetime()),
#   ('Specialization 16', datetime(), datetime()),
#   ('Specialization 17', datetime(), datetime()),
#   ('Specialization 18', datetime(), datetime()),
#   ('Specialization 19', datetime(), datetime()),
#   ('Specialization 20', datetime(), datetime()),
#   ('Specialization 21', datetime(), datetime()),
#   ('Specialization 22', datetime(), datetime()),
#   ('Specialization 23', datetime(), datetime()),
#   ('Specialization 24', datetime(), datetime()),
#   ('Specialization 25', datetime(), datetime()),
#   ('Specialization 26', datetime(), datetime()),
#   ('Specialization 27', datetime(), datetime()),
#   ('Specialization 28', datetime(), datetime()),
#   ('Specialization 29', datetime(), datetime()),
#   ('Specialization 30', datetime(), datetime()),
#   ('Specialization 31', datetime(), datetime()),
#   ('Specialization 32', datetime(), datetime()),
#   ('Specialization 33', datetime(), datetime()),
#   ('Specialization 34', datetime(), datetime()),
#   ('Specialization 35', datetime(), datetime()),
#   ('Specialization 36', datetime(), datetime()),
#   ('Specialization 37', datetime(), datetime()),
#   ('Specialization 38', datetime(), datetime()),
#   ('Specialization 39', datetime(), datetime()),
#   ('Specialization 40', datetime(), datetime()),
#   ('Specialization 41', datetime(), datetime()),
#   ('Specialization 42', datetime(), datetime()),
#   ('Specialization 43', datetime(), datetime()),
#   ('Specialization 44', datetime(), datetime()),
#   ('Specialization 45', datetime(), datetime()),
#   ('Specialization 46', datetime(), datetime()),
#   ('Specialization 47', datetime(), datetime()),
#   ('Specialization 48', datetime(), datetime()),
#   ('Specialization 49', datetime(), datetime()),
#   ('Specialization 50', datetime(), datetime()),
#   ('Specialization 51', datetime(), datetime()),
#   ('Specialization 52', datetime(), datetime()),
#   ('Specialization 53', datetime(), datetime()),
#   ('Specialization 54', datetime(), datetime()),
#   ('Specialization 55', datetime(), datetime()),
#   ('Specialization 56', datetime(), datetime()),
#   ('Specialization 57', datetime(), datetime()),
#   ('Specialization 58', datetime(), datetime()),
#   ('Specialization 59', datetime(), datetime()),
#   ('Specialization 60', datetime(), datetime()),
#   ('Specialization 61', datetime(), datetime()),
#   ('Specialization 62', datetime(), datetime()),
#   ('Specialization 63', datetime(), datetime()),
#   ('Specialization 64', datetime(), datetime()),
#   ('Specialization 65', datetime(), datetime()),
#   ('Specialization 66', datetime(), datetime()),
#   ('Specialization 67', datetime(), datetime()),
#   ('Specialization 68', datetime(), datetime()),
#   ('Specialization 69', datetime(), datetime()),
#   ('Specialization 70', datetime(), datetime()),
#   ('Specialization 71', datetime(), datetime()),
#   ('Specialization 72', datetime(), datetime()),
#   ('Specialization 73', datetime(), datetime()),
#   ('Specialization 74', datetime(), datetime()),
#   ('Specialization 75', datetime(), datetime()),
#   ('Specialization 76', datetime(), datetime()),
#   ('Specialization 77', datetime(), datetime()),
#   ('Specialization 78', datetime(), datetime()),
#   ('Specialization 79', datetime(), datetime()),
#   ('Specialization 80', datetime(), datetime()),
#   ('Specialization 81', datetime(), datetime()),
#   ('Specialization 82', datetime(), datetime()),
#   ('Specialization 83', datetime(), datetime()),
#   ('Specialization 84', datetime(), datetime()),
#   ('Specialization 85', datetime(), datetime()),
#   ('Specialization 86', datetime(), datetime()),
#   ('Specialization 87', datetime(), datetime()),
#   ('Specialization 88', datetime(), datetime()),
#   ('Specialization 89', datetime(), datetime()),
#   ('Specialization 90', datetime(), datetime()),
#   ('Specialization 91', datetime(), datetime()),
#   ('Specialization 92', datetime(), datetime()),
#   ('Specialization 93', datetime(), datetime()),
#   ('Specialization 94', datetime(), datetime()),
#   ('Specialization 95', datetime(), datetime()),
#   ('Specialization 96', datetime(), datetime()),
#   ('Specialization 97', datetime(), datetime()),
#   ('Specialization 98', datetime(), datetime()),
#   ('Specialization 99', datetime(), datetime()),
#   ('Specialization 100', datetime(), datetime())")
#
# doctors = Doctor.create([{ name: "Doctor 1", experience_in_years: 1, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 2", experience_in_years: 2, repartment_id: 1, specialization_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 3", experience_in_years: 3, repartment_id: 2, specialization_id: 15, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 4", experience_in_years: 4, repartment_id: 3, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 5", experience_in_years: 5, repartment_id: 4, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 6", experience_in_years: 6, repartment_id: 5, specialization_id: 31, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 7", experience_in_years: 7, repartment_id: 6, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 8", experience_in_years: 8, repartment_id: 7, specialization_id: 2, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 9", experience_in_years: 9, repartment_id: 8, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 10", experience_in_years: 10, repartment_id: 9, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 11", experience_in_years: 11, repartment_id: 10, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 12", experience_in_years: 12, repartment_id: 11, specialization_id: 61, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 13", experience_in_years: 13, repartment_id: 12, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 14", experience_in_years: 14, repartment_id: 13, specialization_id: 17, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 15", experience_in_years: 15, repartment_id: 14, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 16", experience_in_years: 16, repartment_id: 15, specialization_id: 13, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 17", experience_in_years: 17, repartment_id: 16, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 18", experience_in_years: 18, repartment_id: 17, specialization_id: 11, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 19", experience_in_years: 19, repartment_id: 18, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 20", experience_in_years: 20, repartment_id: 19, specialization_id: 14, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 21", experience_in_years: 21, repartment_id: 20, specialization_id: 11, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 22", experience_in_years: 22, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 23", experience_in_years: 23, repartment_id: 12, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 24", experience_in_years: 24, repartment_id: 11, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 25", experience_in_years: 25, repartment_id: 13, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 26", experience_in_years: 1, repartment_id: 16, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 27", experience_in_years: 2, repartment_id: 11, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 28", experience_in_years: 3, repartment_id: 30, specialization_id: 14, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 29", experience_in_years: 4, repartment_id: 11, specialization_id: 15, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 30", experience_in_years: 5, repartment_id: 19, specialization_id: 16, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 31", experience_in_years: 6, repartment_id: 23, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 32", experience_in_years: 7, repartment_id: 26, specialization_id: 71, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 33", experience_in_years: 8, repartment_id: 11, specialization_id: 81, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 34", experience_in_years: 9, repartment_id: 44, specialization_id: 19, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 35", experience_in_years: 10, repartment_id: 55, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 36", experience_in_years: 11, repartment_id: 66, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 37", experience_in_years: 12, repartment_id: 54, specialization_id: 11, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 38", experience_in_years: 13, repartment_id: 43, specialization_id: 31, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 39", experience_in_years: 14, repartment_id: 33, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 40", experience_in_years: 15, repartment_id: 77, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 41", experience_in_years: 16, repartment_id: 55, specialization_id: 31, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 42", experience_in_years: 17, repartment_id: 55, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 43", experience_in_years: 18, repartment_id: 44, specialization_id: 21, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 44", experience_in_years: 19, repartment_id: 33, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 45", experience_in_years: 20, repartment_id: 36, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 46", experience_in_years: 21, repartment_id: 69, specialization_id: 11, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 47", experience_in_years: 22, repartment_id: 76, specialization_id: 41, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 48", experience_in_years: 23, repartment_id: 45, specialization_id: 13, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 49", experience_in_years: 24, repartment_id: 75, specialization_id: 21, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 50", experience_in_years: 25, repartment_id: 10, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 51", experience_in_years: 1, repartment_id: 13, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 52", experience_in_years: 2, repartment_id: 17, specialization_id: 41, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 53", experience_in_years: 3, repartment_id: 14, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 54", experience_in_years: 4, repartment_id: 17, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 55", experience_in_years: 5, repartment_id: 11, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 56", experience_in_years: 6, repartment_id: 64, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 57", experience_in_years: 7, repartment_id: 16, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 58", experience_in_years: 8, repartment_id: 41, specialization_id: 51, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 59", experience_in_years: 9, repartment_id: 13, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 60", experience_in_years: 10, repartment_id: 71, specialization_id: 61, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 61", experience_in_years: 11, repartment_id: 71, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 62", experience_in_years: 12, repartment_id: 31, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 63", experience_in_years: 13, repartment_id: 6, specialization_id: 17, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 64", experience_in_years: 14, repartment_id: 41, specialization_id: 81, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 65", experience_in_years: 15, repartment_id: 61, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 66", experience_in_years: 16, repartment_id: 71, specialization_id: 19, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 67", experience_in_years: 17, repartment_id: 41, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 68", experience_in_years: 18, repartment_id: 31, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 69", experience_in_years: 19, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 70", experience_in_years: 20, repartment_id: 61, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 71", experience_in_years: 21, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 72", experience_in_years: 22, repartment_id: 61, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 73", experience_in_years: 23, repartment_id: 1, specialization_id: 11, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 74", experience_in_years: 24, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 75", experience_in_years: 25, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 76", experience_in_years: 1, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 77", experience_in_years: 2, repartment_id: 11, specialization_id: 41, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 78", experience_in_years: 3, repartment_id: 21, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 79", experience_in_years: 4, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 80", experience_in_years: 5, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 81", experience_in_years: 6, repartment_id: 31, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 82", experience_in_years: 7, repartment_id: 1, specialization_id: 16, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 83", experience_in_years: 8, repartment_id: 14, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 84", experience_in_years: 9, repartment_id: 14, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 85", experience_in_years: 10, repartment_id: 1, specialization_id: 71, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 86", experience_in_years: 11, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 87", experience_in_years: 12, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 88", experience_in_years: 13, repartment_id: 51, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 89", experience_in_years: 14, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 90", experience_in_years: 15, repartment_id: 1, specialization_id: 18, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 91", experience_in_years: 16, repartment_id: 17, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 92", experience_in_years: 17, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 93", experience_in_years: 18, repartment_id: 81, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 94", experience_in_years: 19, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 95", experience_in_years: 20, repartment_id: 1, specialization_id: 11, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 96", experience_in_years: 21, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 97", experience_in_years: 22, repartment_id: 1, specialization_id: 14, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 98", experience_in_years: 23, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 99", experience_in_years: 24, repartment_id: 1, specialization_id: 21, created_at: Date.today.to_s, updated_at: Date.today.to_s },
#                          { name: "Doctor 100", experience_in_years: 25, repartment_id: 1, specialization_id: 1, created_at: Date.today.to_s, updated_at: Date.today.to_s }])
#
# connection.execute("INSERT INTO Pacients(name, age, diagnosis, created_at, updated_at) VALUES
# ('Pacient 1', 20, 'Diagnosis 1', datetime(), datetime()),
# ('Pacient 2', 20, 'Diagnosis 2', datetime(), datetime()),
# ('Pacient 3', 20, 'Diagnosis 3', datetime(), datetime()),
# ('Pacient 4', 20, 'Diagnosis 4', datetime(), datetime()),
# ('Pacient 5', 21, 'Diagnosis 5', datetime(), datetime()),
# ('Pacient 6', 21, 'Diagnosis 6', datetime(), datetime()),
# ('Pacient 7', 21, 'Diagnosis 7', datetime(), datetime()),
# ('Pacient 8', 21, 'Diagnosis 8', datetime(), datetime()),
# ('Pacient 9', 22, 'Diagnosis 9', datetime(), datetime()),
# ('Pacient 10', 22, 'Diagnosis 10', datetime(), datetime()),
# ('Pacient 11', 22, 'Diagnosis 11', datetime(), datetime()),
# ('Pacient 12', 22, 'Diagnosis 12', datetime(), datetime()),
# ('Pacient 13', 23, 'Diagnosis 13', datetime(), datetime()),
# ('Pacient 14', 23, 'Diagnosis 14', datetime(), datetime()),
# ('Pacient 15', 23, 'Diagnosis 15', datetime(), datetime()),
# ('Pacient 16', 23, 'Diagnosis 16', datetime(), datetime()),
# ('Pacient 17', 24, 'Diagnosis 17', datetime(), datetime()),
# ('Pacient 18', 24, 'Diagnosis 18', datetime(), datetime()),
# ('Pacient 19', 24, 'Diagnosis 19', datetime(), datetime()),
# ('Pacient 20', 24, 'Diagnosis 20', datetime(), datetime()),
# ('Pacient 21', 25, 'Diagnosis 21', datetime(), datetime()),
# ('Pacient 22', 25, 'Diagnosis 22', datetime(), datetime()),
# ('Pacient 23', 25, 'Diagnosis 23', datetime(), datetime()),
# ('Pacient 24', 25, 'Diagnosis 24', datetime(), datetime()),
# ('Pacient 25', 26, 'Diagnosis 25', datetime(), datetime()),
# ('Pacient 26', 26, 'Diagnosis 26', datetime(), datetime()),
# ('Pacient 27', 26, 'Diagnosis 27', datetime(), datetime()),
# ('Pacient 28', 26, 'Diagnosis 28', datetime(), datetime()),
# ('Pacient 29', 27, 'Diagnosis 29', datetime(), datetime()),
# ('Pacient 30', 27, 'Diagnosis 30', datetime(), datetime()),
# ('Pacient 31', 27, 'Diagnosis 31', datetime(), datetime()),
# ('Pacient 32', 27, 'Diagnosis 32', datetime(), datetime()),
# ('Pacient 33', 28, 'Diagnosis 33', datetime(), datetime()),
# ('Pacient 34', 28, 'Diagnosis 34', datetime(), datetime()),
# ('Pacient 35', 28, 'Diagnosis 35', datetime(), datetime()),
# ('Pacient 36', 28, 'Diagnosis 36', datetime(), datetime()),
# ('Pacient 37', 29, 'Diagnosis 37', datetime(), datetime()),
# ('Pacient 38', 29, 'Diagnosis 38', datetime(), datetime()),
# ('Pacient 39', 29, 'Diagnosis 39', datetime(), datetime()),
# ('Pacient 40', 29, 'Diagnosis 40', datetime(), datetime()),
# ('Pacient 41', 30, 'Diagnosis 41', datetime(), datetime()),
# ('Pacient 42', 30, 'Diagnosis 42', datetime(), datetime()),
# ('Pacient 43', 30, 'Diagnosis 43', datetime(), datetime()),
# ('Pacient 44', 30, 'Diagnosis 44', datetime(), datetime()),
# ('Pacient 45', 31, 'Diagnosis 45', datetime(), datetime()),
# ('Pacient 46', 31, 'Diagnosis 46', datetime(), datetime()),
# ('Pacient 47', 31, 'Diagnosis 47', datetime(), datetime()),
# ('Pacient 48', 31, 'Diagnosis 48', datetime(), datetime()),
# ('Pacient 49', 32, 'Diagnosis 49', datetime(), datetime()),
# ('Pacient 50', 32, 'Diagnosis 50', datetime(), datetime()),
# ('Pacient 51', 32, 'Diagnosis 51', datetime(), datetime()),
# ('Pacient 52', 32, 'Diagnosis 52', datetime(), datetime()),
# ('Pacient 53', 33, 'Diagnosis 53', datetime(), datetime()),
# ('Pacient 54', 33, 'Diagnosis 54', datetime(), datetime()),
# ('Pacient 55', 33, 'Diagnosis 55', datetime(), datetime()),
# ('Pacient 56', 33, 'Diagnosis 56', datetime(), datetime()),
# ('Pacient 57', 34, 'Diagnosis 57', datetime(), datetime()),
# ('Pacient 58', 34, 'Diagnosis 58', datetime(), datetime()),
# ('Pacient 59', 34, 'Diagnosis 59', datetime(), datetime()),
# ('Pacient 60', 34, 'Diagnosis 60', datetime(), datetime()),
# ('Pacient 61', 35, 'Diagnosis 61', datetime(), datetime()),
# ('Pacient 62', 35, 'Diagnosis 62', datetime(), datetime()),
# ('Pacient 63', 35, 'Diagnosis 63', datetime(), datetime()),
# ('Pacient 64', 35, 'Diagnosis 64', datetime(), datetime()),
# ('Pacient 65', 36, 'Diagnosis 65', datetime(), datetime()),
# ('Pacient 66', 36, 'Diagnosis 66', datetime(), datetime()),
# ('Pacient 67', 36, 'Diagnosis 67', datetime(), datetime()),
# ('Pacient 68', 36, 'Diagnosis 68', datetime(), datetime()),
# ('Pacient 69', 37, 'Diagnosis 69', datetime(), datetime()),
# ('Pacient 70', 37, 'Diagnosis 70', datetime(), datetime()),
# ('Pacient 71', 37, 'Diagnosis 71', datetime(), datetime()),
# ('Pacient 72', 37, 'Diagnosis 72', datetime(), datetime()),
# ('Pacient 73', 38, 'Diagnosis 73', datetime(), datetime()),
# ('Pacient 74', 38, 'Diagnosis 74', datetime(), datetime()),
# ('Pacient 75', 38, 'Diagnosis 75', datetime(), datetime()),
# ('Pacient 76', 38, 'Diagnosis 76', datetime(), datetime()),
# ('Pacient 77', 39, 'Diagnosis 77', datetime(), datetime()),
# ('Pacient 78', 39, 'Diagnosis 78', datetime(), datetime()),
# ('Pacient 79', 39, 'Diagnosis 79', datetime(), datetime()),
# ('Pacient 80', 39, 'Diagnosis 80', datetime(), datetime()),
# ('Pacient 81', 40, 'Diagnosis 81', datetime(), datetime()),
# ('Pacient 82', 40, 'Diagnosis 82', datetime(), datetime()),
# ('Pacient 83', 40, 'Diagnosis 83', datetime(), datetime()),
# ('Pacient 84', 40, 'Diagnosis 84', datetime(), datetime()),
# ('Pacient 85', 41, 'Diagnosis 85', datetime(), datetime()),
# ('Pacient 86', 41, 'Diagnosis 86', datetime(), datetime()),
# ('Pacient 87', 41, 'Diagnosis 87', datetime(), datetime()),
# ('Pacient 88', 41, 'Diagnosis 88', datetime(), datetime()),
# ('Pacient 89', 42, 'Diagnosis 89', datetime(), datetime()),
# ('Pacient 90', 42, 'Diagnosis 90', datetime(), datetime()),
# ('Pacient 91', 42, 'Diagnosis 91', datetime(), datetime()),
# ('Pacient 92', 42, 'Diagnosis 92', datetime(), datetime()),
# ('Pacient 93', 43, 'Diagnosis 93', datetime(), datetime()),
# ('Pacient 94', 43, 'Diagnosis 94', datetime(), datetime()),
# ('Pacient 95', 43, 'Diagnosis 95', datetime(), datetime()),
# ('Pacient 96', 43, 'Diagnosis 96', datetime(), datetime()),
# ('Pacient 97', 44, 'Diagnosis 97', datetime(), datetime()),
# ('Pacient 98', 44, 'Diagnosis 98', datetime(), datetime()),
# ('Pacient 99', 44, 'Diagnosis 99', datetime(), datetime()),
# ('Pacient 100', 44, 'Diagnosis 100', datetime(), datetime())")
#
# connection.execute("INSERT INTO Medcards(name, year, pacient_id, clinic_id, created_at, updated_at) VALUES
# ('Medcard 1', 2019, 1, 1, datetime(), datetime()),
# ('Medcard 2', 2019, 2, 1, datetime(), datetime()),
# ('Medcard 3', 2019, 3, 1, datetime(), datetime()),
# ('Medcard 4', 2019, 4, 13, datetime(), datetime()),
# ('Medcard 5', 2019, 5, 1, datetime(), datetime()),
# ('Medcard 6', 2019, 6, 1, datetime(), datetime()),
# ('Medcard 7', 2019, 7, 16, datetime(), datetime()),
# ('Medcard 8', 2019, 8, 1, datetime(), datetime()),
# ('Medcard 9', 2019, 9, 1, datetime(), datetime()),
# ('Medcard 10', 2019, 10, 2, datetime(), datetime()),
# ('Medcard 11', 2019, 11, 2, datetime(), datetime()),
# ('Medcard 12', 2019, 12, 2, datetime(), datetime()),
# ('Medcard 13', 2019, 13, 3, datetime(), datetime()),
# ('Medcard 14', 2019, 14, 5, datetime(), datetime()),
# ('Medcard 15', 2019, 15, 7, datetime(), datetime()),
# ('Medcard 16', 2019, 16, 1, datetime(), datetime()),
# ('Medcard 17', 2019, 17, 31, datetime(), datetime()),
# ('Medcard 18', 2019, 18, 1, datetime(), datetime()),
# ('Medcard 19', 2019, 19, 41, datetime(), datetime()),
# ('Medcard 20', 2019, 20, 1, datetime(), datetime()),
# ('Medcard 21', 2019, 21, 1, datetime(), datetime()),
# ('Medcard 22', 2019, 22, 14, datetime(), datetime()),
# ('Medcard 23', 2019, 23, 1, datetime(), datetime()),
# ('Medcard 24', 2019, 24, 41, datetime(), datetime()),
# ('Medcard 25', 2019, 25, 1, datetime(), datetime()),
# ('Medcard 26', 2020, 26, 41, datetime(), datetime()),
# ('Medcard 27', 2020, 27, 1, datetime(), datetime()),
# ('Medcard 28', 2020, 28, 1, datetime(), datetime()),
# ('Medcard 29', 2020, 29, 1, datetime(), datetime()),
# ('Medcard 30', 2020, 30, 51, datetime(), datetime()),
# ('Medcard 31', 2020, 31, 1, datetime(), datetime()),
# ('Medcard 32', 2020, 32, 17, datetime(), datetime()),
# ('Medcard 33', 2020, 33, 1, datetime(), datetime()),
# ('Medcard 34', 2020, 35, 1, datetime(), datetime()),
# ('Medcard 35', 2020, 1, 1, datetime(), datetime()),
# ('Medcard 36', 2020, 1, 1, datetime(), datetime()),
# ('Medcard 37', 2020, 15, 17, datetime(), datetime()),
# ('Medcard 38', 2020, 61, 1, datetime(), datetime()),
# ('Medcard 39', 2020, 17, 1, datetime(), datetime()),
# ('Medcard 40', 2020, 1, 1, datetime(), datetime()),
# ('Medcard 41', 2020, 11, 81, datetime(), datetime()),
# ('Medcard 42', 2020, 1, 55, datetime(), datetime()),
# ('Medcard 43', 2020, 61, 1, datetime(), datetime()),
# ('Medcard 44', 2020, 1, 1, datetime(), datetime()),
# ('Medcard 45', 2020, 1, 1, datetime(), datetime()),
# ('Medcard 46', 2020, 61, 44, datetime(), datetime()),
# ('Medcard 47', 2020, 31, 1, datetime(), datetime()),
# ('Medcard 48', 2020, 1, 47, datetime(), datetime()),
# ('Medcard 49', 2020, 41, 1, datetime(), datetime()),
# ('Medcard 50', 2020, 61, 41, datetime(), datetime()),
# ('Medcard 51', 2021, 33, 1, datetime(), datetime()),
# ('Medcard 52', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 53', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 54', 2021, 1, 42, datetime(), datetime()),
# ('Medcard 55', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 56', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 57', 2021, 66, 47, datetime(), datetime()),
# ('Medcard 58', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 59', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 60', 2021, 55, 1, datetime(), datetime()),
# ('Medcard 61', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 62', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 63', 2021, 15, 55, datetime(), datetime()),
# ('Medcard 64', 2021, 44, 1, datetime(), datetime()),
# ('Medcard 65', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 66', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 67', 2021, 55, 75, datetime(), datetime()),
# ('Medcard 68', 2021, 66, 1, datetime(), datetime()),
# ('Medcard 69', 2021, 77, 1, datetime(), datetime()),
# ('Medcard 70', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 71', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 72', 2021, 15, 1, datetime(), datetime()),
# ('Medcard 73', 2021, 1, 46, datetime(), datetime()),
# ('Medcard 74', 2021, 1, 1, datetime(), datetime()),
# ('Medcard 75', 2021, 14, 1, datetime(), datetime()),
# ('Medcard 76', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 77', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 78', 2022, 71, 1, datetime(), datetime()),
# ('Medcard 79', 2022, 1, 62, datetime(), datetime()),
# ('Medcard 80', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 81', 2022, 61, 1, datetime(), datetime()),
# ('Medcard 82', 2022, 1, 74, datetime(), datetime()),
# ('Medcard 83', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 84', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 85', 2022, 53, 1, datetime(), datetime()),
# ('Medcard 86', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 87', 2022, 17, 1, datetime(), datetime()),
# ('Medcard 88', 2022, 88, 77, datetime(), datetime()),
# ('Medcard 89', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 90', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 91', 2022, 16, 1, datetime(), datetime()),
# ('Medcard 92', 2022, 1, 21, datetime(), datetime()),
# ('Medcard 93', 2022, 31, 1, datetime(), datetime()),
# ('Medcard 94', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 95', 2022, 1, 1, datetime(), datetime()),
# ('Medcard 96', 2022, 91, 1, datetime(), datetime()),
# ('Medcard 97', 2022, 41, 1, datetime(), datetime()),
# ('Medcard 98', 2022, 1, 44, datetime(), datetime()),
# ('Medcard 99', 2022, 51, 1, datetime(), datetime()),
# ('Medcard 100', 2022, 9, 9, datetime(), datetime())")
#
# Clinic.where(id: 1).update(name: 'Main Clinic')
# Repartment.where(id:5).update(block: 'Restricted')
# Doctor.where(id: 6).update(experience_in_years: 30)
# connection.execute("UPDATE specializations SET name = 'Dantist' WHERE id = 2")
# connection.execute("UPDATE medcards SET year = 2016 WHERE id = 5")
# connection.execute("UPDATE pacients SET age = 92 WHERE id = 9")
#
# connection.execute("DROP VIEW IF EXISTS DoctorsAndSpec")
# connection.execute("CREATE VIEW DoctorsAndSpec AS SELECT doctors.name, doctors.experience_in_years, specializations.name
# FROM doctors INNER JOIN specializations ON doctors.specialization_id = specializations.id")
# connection.execute("DROP VIEW IF EXISTS MedcardsAndPacients")
# connection.execute("CREATE VIEW MedcardsAndPacients AS SELECT pacients.name, pacients.diagnosis, medcards.name
# FROM pacients INNER JOIN medcards ON pacients.id = medcards.pacient_id")

# require 'faker'
# i = 0
# while(i < 100)
#   Pacient.where(id: i).update(name: Faker::Name.name)
#   Pacient.where(id: i).update(diagnosis: Faker::Science.element)
#   Doctor.where(id: i).update(name: Faker::Name.name)
#   i += 1
# end
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?